# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CNV322_development
  username: <%= ENV["CNV322_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["CNV322_DEV_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: CNV322_test
  username: <%= ENV["CNV322_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["CNV322_DEV_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: CNV322_production
  username: CNV322
  password: <%= ENV["CNV322_DATABASE_PASSWORD"] %>